/**
 * @module knowledge-graph/tag-concept-map
 * @description Maps problem.tags[] and problem.primary_pattern values to
 *              DSA concept slugs used in concept_states.
 *              Single source of truth — imported by KG service and AnalysisClient.
 */
// @ts-nocheck


export const PROBLEM_TAG_TO_CONCEPT_SLUG: Record<string, string | null> = {
  arrays: 'arrays-strings',
  array: 'arrays-strings',
  strings: 'arrays-strings',
  string: 'arrays-strings',
  'string-matching': 'arrays-strings',
  'string matching': 'arrays-strings',
  anagram: 'arrays-strings',
  hashing: 'hashmaps-sets',
  hashmap: 'hashmaps-sets',
  'hash-map': 'hashmaps-sets',
  'hash map': 'hashmaps-sets',
  'hash-table': 'hashmaps-sets',
  'hash table': 'hashmaps-sets',
  hashset: 'hashmaps-sets',
  set: 'hashmaps-sets',
  'ordered-set': 'hashmaps-sets',
  'two-pointer': 'two-pointers',
  'two-pointers': 'two-pointers',
  'two pointers': 'two-pointers',
  'sliding-window': 'sliding-window',
  'sliding window': 'sliding-window',
  'binary-search': 'binary-search',
  'binary search': 'binary-search',
  recursion: 'recursion-backtracking',
  backtracking: 'recursion-backtracking',
  trees: 'trees-traversal',
  tree: 'trees-traversal',
  traversal: 'trees-traversal',
  'binary-tree': 'trees-traversal',
  'binary-search-tree': 'trees-traversal',
  'binary search tree': 'trees-traversal',
  graphs: 'graphs-bfs-dfs',
  graph: 'graphs-bfs-dfs',
  bfs: 'graphs-bfs-dfs',
  dfs: 'graphs-bfs-dfs',
  'breadth-first-search': 'graphs-bfs-dfs',
  'breadth-first search': 'graphs-bfs-dfs',
  'depth-first-search': 'graphs-bfs-dfs',
  'depth-first search': 'graphs-bfs-dfs',
  "dijkstra's-algorithm": 'graphs-bfs-dfs',
  "dijkstra's algorithm": 'graphs-bfs-dfs',
  "floyd-warshall-algorithm": 'graphs-bfs-dfs',
  "floyd-warshall algorithm": 'graphs-bfs-dfs',
  'topological-sort': 'graphs-bfs-dfs',
  'topological sort': 'graphs-bfs-dfs',
  'shortest path': 'graphs-bfs-dfs',
  'dynamic-programming': 'dynamic-programming',
  'dynamic programming': 'dynamic-programming',
  dp: 'dynamic-programming',
  memoization: 'dynamic-programming',
  tabulation: 'dynamic-programming',
  heap: 'heaps',
  heaps: 'heaps',
  'priority-queue': 'heaps',
  'priority queue': 'heaps',
  'heap-(priority-queue)': 'heaps',
  'heap (priority queue)': 'heaps',
  trie: 'tries',
  tries: 'tries',
  sorting: 'sorting-algorithms',
  sort: 'sorting-algorithms',
  'merge-sort': 'sorting-algorithms',
  'bucket-sort': 'sorting-algorithms',
  quickselect: 'sorting-algorithms',
  'linked-list': 'linked-lists',
  'linked-lists': 'linked-lists',
  'linked list': 'linked-lists',
  'doubly-linked-list': 'linked-lists',
  'doubly linked list': 'linked-lists',
  "floyd's-tortoise-and-hare": 'linked-lists',
  "floyd's tortoise and hare": 'linked-lists',
  'bit-manipulation': 'bit-manipulation',
  'bit manipulation': 'bit-manipulation',
  bits: 'bit-manipulation',
  binary: 'bit-manipulation',
  'prefix-xor': 'bit-manipulation',
  'prefix xor': 'bit-manipulation',
  math: 'math-number-theory',
  'number-theory': 'math-number-theory',
  geometry: 'math-number-theory',
  gcd: 'math-number-theory',
  probability: 'math-number-theory',
  combinatorics: 'math-number-theory',
  counting: 'math-number-theory',
  median: 'math-number-theory',
  stack: 'stack-queue',
  queue: 'stack-queue',
  'monotonic-stack': 'stack-queue',
  'monotonic-queue': 'stack-queue',
  intervals: 'intervals',
  matrix: 'matrix',
  grid: 'matrix',
  'prefix-sum': 'prefix-sum',
  'prefix sum': 'prefix-sum',
  'union-find': 'union-find',
  'union find': 'union-find',
  'disjoint-set': 'union-find',
  'binary-indexed-tree': null,
  'segment-tree': null,
};

export const INTENTIONALLY_UNMAPPED_TAGS = new Set([
  'simulation',
  'design',
  'interactive',
  'greedy',
  'divide-and-conquer',
  'data stream',
  'data-stream',
  'brainteaser',
  'game-theory',
  'random',
  'rejection sampling',
  'state machine',
  'list comprehension',
  'lru cache',
  'data structures',
  "kadane's algorithm",
  'dutch national flag algorithm',
  "boyer-moore majority vote",
  'constant time complexity',
  'ratio optimization',
  'blind 75',
  'grind 75',
  'neetcode 150',
  'striver a-z',
  "striver's a-z dsa sheet",
]);

export function tagsToConceptSlugs(tags: string[], primaryPattern?: string | null): string[] {
  const combined = primaryPattern ? [...tags, primaryPattern] : tags;
  const mapped = combined
    .map((tag) => PROBLEM_TAG_TO_CONCEPT_SLUG[tag.toLowerCase()])
    .filter((slug): slug is string => slug !== undefined && slug !== null);
  return [...new Set(mapped)];
}

export function tagsToFirstConceptSlug(tags: string[], primaryPattern?: string | null): string | null {
  const slugs = tagsToConceptSlugs(tags, primaryPattern);
  return slugs[0] ?? null;
}
