export const DSA_VOCABULARY = [
    'binary tree', 'binary search tree', 'BST',
    'hash map', 'hash table', 'hash set',
    'linked list', 'doubly linked list',
    'stack', 'queue', 'priority queue', 'heap',
    'min heap', 'max heap',
    'graph', 'vertex', 'edge', 'adjacency matrix', 'adjacency list',
    'trie', 'prefix tree',
    'breadth first search', 'BFS',
    'depth first search', 'DFS',
    'dynamic programming', 'DP', 'memoization', 'tabulation',
    'recursion', 'recursive',
    'backtracking',
    'greedy', 'greedy algorithm',
    'divide and conquer',
    'sliding window',
    'two pointers',
    'bit manipulation', 'XOR', 'AND', 'OR', 'bit shift',
    'time complexity', 'space complexity',
    'big O', 'O of n', 'O of log n', 'O of n squared',
    'array', 'string', 'matrix',
    'sorting', 'merge sort', 'quick sort', 'heap sort', 'bubble sort', 'insertion sort',
    'searching', 'binary search',
    'palindrome', 'anagram', 'substring', 'subsequence',
    'tree traversal', 'inorder', 'preorder', 'postorder', 'level order',
    'shortest path', 'Dijkstra', 'Bellman Ford', 'Floyd Warshall',
    'minimum spanning tree', 'Prim', 'Kruskal',
    'topological sort', 'union find', 'disjoint set'
];
